// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: proto/pipeline/tree.proto

package pipeline

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PipelineInitTree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *PipelineInitTree_Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Secret  *PipelineInitTree_Secret  `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *PipelineInitTree) Reset() {
	*x = PipelineInitTree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree) ProtoMessage() {}

func (x *PipelineInitTree) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree.ProtoReflect.Descriptor instead.
func (*PipelineInitTree) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0}
}

func (x *PipelineInitTree) GetAccount() *PipelineInitTree_Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *PipelineInitTree) GetSecret() *PipelineInitTree_Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type PipelineInitTree_Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Register *PipelineInitTree_Account_Register `protobuf:"bytes,1,opt,name=register,proto3" json:"register,omitempty"`
}

func (x *PipelineInitTree_Account) Reset() {
	*x = PipelineInitTree_Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Account) ProtoMessage() {}

func (x *PipelineInitTree_Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Account.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Account) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PipelineInitTree_Account) GetRegister() *PipelineInitTree_Account_Register {
	if x != nil {
		return x.Register
	}
	return nil
}

type PipelineInitTree_Secret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text          *PipelineInitTree_Secret_Text          `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	LoginPassword *PipelineInitTree_Secret_LoginPassword `protobuf:"bytes,2,opt,name=login_password,json=loginPassword,proto3" json:"login_password,omitempty"`
	CreditCard    *PipelineInitTree_Secret_CreditCard    `protobuf:"bytes,3,opt,name=credit_card,json=creditCard,proto3" json:"credit_card,omitempty"`
	File          *PipelineInitTree_Secret_File          `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	List          *PipelineInitTree_Secret_List          `protobuf:"bytes,99,opt,name=list,proto3" json:"list,omitempty"`
}

func (x *PipelineInitTree_Secret) Reset() {
	*x = PipelineInitTree_Secret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret) ProtoMessage() {}

func (x *PipelineInitTree_Secret) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PipelineInitTree_Secret) GetText() *PipelineInitTree_Secret_Text {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *PipelineInitTree_Secret) GetLoginPassword() *PipelineInitTree_Secret_LoginPassword {
	if x != nil {
		return x.LoginPassword
	}
	return nil
}

func (x *PipelineInitTree_Secret) GetCreditCard() *PipelineInitTree_Secret_CreditCard {
	if x != nil {
		return x.CreditCard
	}
	return nil
}

func (x *PipelineInitTree_Secret) GetFile() *PipelineInitTree_Secret_File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *PipelineInitTree_Secret) GetList() *PipelineInitTree_Secret_List {
	if x != nil {
		return x.List
	}
	return nil
}

type PipelineInitTree_Account_Register struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *PipelineInitTree_Account_Register) Reset() {
	*x = PipelineInitTree_Account_Register{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Account_Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Account_Register) ProtoMessage() {}

func (x *PipelineInitTree_Account_Register) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Account_Register.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Account_Register) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *PipelineInitTree_Account_Register) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *PipelineInitTree_Account_Register) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PipelineInitTree_Secret_Text struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Get    *PipelineInitTree_Secret_Text_Get    `protobuf:"bytes,1,opt,name=get,proto3" json:"get,omitempty"`
	Create *PipelineInitTree_Secret_Text_Create `protobuf:"bytes,2,opt,name=create,proto3" json:"create,omitempty"`
	Update *PipelineInitTree_Secret_Text_Update `protobuf:"bytes,3,opt,name=update,proto3" json:"update,omitempty"`
	Delete *PipelineInitTree_Secret_Text_Delete `protobuf:"bytes,4,opt,name=delete,proto3" json:"delete,omitempty"`
}

func (x *PipelineInitTree_Secret_Text) Reset() {
	*x = PipelineInitTree_Secret_Text{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_Text) ProtoMessage() {}

func (x *PipelineInitTree_Secret_Text) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_Text.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_Text) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *PipelineInitTree_Secret_Text) GetGet() *PipelineInitTree_Secret_Text_Get {
	if x != nil {
		return x.Get
	}
	return nil
}

func (x *PipelineInitTree_Secret_Text) GetCreate() *PipelineInitTree_Secret_Text_Create {
	if x != nil {
		return x.Create
	}
	return nil
}

func (x *PipelineInitTree_Secret_Text) GetUpdate() *PipelineInitTree_Secret_Text_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *PipelineInitTree_Secret_Text) GetDelete() *PipelineInitTree_Secret_Text_Delete {
	if x != nil {
		return x.Delete
	}
	return nil
}

type PipelineInitTree_Secret_LoginPassword struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Get    *PipelineInitTree_Secret_LoginPassword_Get    `protobuf:"bytes,1,opt,name=get,proto3" json:"get,omitempty"`
	Create *PipelineInitTree_Secret_LoginPassword_Create `protobuf:"bytes,2,opt,name=create,proto3" json:"create,omitempty"`
	Update *PipelineInitTree_Secret_LoginPassword_Update `protobuf:"bytes,3,opt,name=update,proto3" json:"update,omitempty"`
	Delete *PipelineInitTree_Secret_LoginPassword_Delete `protobuf:"bytes,4,opt,name=delete,proto3" json:"delete,omitempty"`
}

func (x *PipelineInitTree_Secret_LoginPassword) Reset() {
	*x = PipelineInitTree_Secret_LoginPassword{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_LoginPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_LoginPassword) ProtoMessage() {}

func (x *PipelineInitTree_Secret_LoginPassword) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_LoginPassword.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_LoginPassword) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *PipelineInitTree_Secret_LoginPassword) GetGet() *PipelineInitTree_Secret_LoginPassword_Get {
	if x != nil {
		return x.Get
	}
	return nil
}

func (x *PipelineInitTree_Secret_LoginPassword) GetCreate() *PipelineInitTree_Secret_LoginPassword_Create {
	if x != nil {
		return x.Create
	}
	return nil
}

func (x *PipelineInitTree_Secret_LoginPassword) GetUpdate() *PipelineInitTree_Secret_LoginPassword_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *PipelineInitTree_Secret_LoginPassword) GetDelete() *PipelineInitTree_Secret_LoginPassword_Delete {
	if x != nil {
		return x.Delete
	}
	return nil
}

type PipelineInitTree_Secret_CreditCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Get    *PipelineInitTree_Secret_CreditCard_Get    `protobuf:"bytes,1,opt,name=get,proto3" json:"get,omitempty"`
	Create *PipelineInitTree_Secret_CreditCard_Create `protobuf:"bytes,2,opt,name=create,proto3" json:"create,omitempty"`
	Update *PipelineInitTree_Secret_CreditCard_Update `protobuf:"bytes,3,opt,name=update,proto3" json:"update,omitempty"`
	Delete *PipelineInitTree_Secret_CreditCard_Delete `protobuf:"bytes,4,opt,name=delete,proto3" json:"delete,omitempty"`
}

func (x *PipelineInitTree_Secret_CreditCard) Reset() {
	*x = PipelineInitTree_Secret_CreditCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_CreditCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_CreditCard) ProtoMessage() {}

func (x *PipelineInitTree_Secret_CreditCard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_CreditCard.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_CreditCard) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 2}
}

func (x *PipelineInitTree_Secret_CreditCard) GetGet() *PipelineInitTree_Secret_CreditCard_Get {
	if x != nil {
		return x.Get
	}
	return nil
}

func (x *PipelineInitTree_Secret_CreditCard) GetCreate() *PipelineInitTree_Secret_CreditCard_Create {
	if x != nil {
		return x.Create
	}
	return nil
}

func (x *PipelineInitTree_Secret_CreditCard) GetUpdate() *PipelineInitTree_Secret_CreditCard_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *PipelineInitTree_Secret_CreditCard) GetDelete() *PipelineInitTree_Secret_CreditCard_Delete {
	if x != nil {
		return x.Delete
	}
	return nil
}

type PipelineInitTree_Secret_File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Download *PipelineInitTree_Secret_File_Download `protobuf:"bytes,1,opt,name=download,proto3" json:"download,omitempty"`
	Upload   *PipelineInitTree_Secret_File_Upload   `protobuf:"bytes,2,opt,name=upload,proto3" json:"upload,omitempty"`
	Update   *PipelineInitTree_Secret_File_Update   `protobuf:"bytes,3,opt,name=update,proto3" json:"update,omitempty"`
	Delete   *PipelineInitTree_Secret_File_Delete   `protobuf:"bytes,4,opt,name=delete,proto3" json:"delete,omitempty"`
}

func (x *PipelineInitTree_Secret_File) Reset() {
	*x = PipelineInitTree_Secret_File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_File) ProtoMessage() {}

func (x *PipelineInitTree_Secret_File) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_File.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_File) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 3}
}

func (x *PipelineInitTree_Secret_File) GetDownload() *PipelineInitTree_Secret_File_Download {
	if x != nil {
		return x.Download
	}
	return nil
}

func (x *PipelineInitTree_Secret_File) GetUpload() *PipelineInitTree_Secret_File_Upload {
	if x != nil {
		return x.Upload
	}
	return nil
}

func (x *PipelineInitTree_Secret_File) GetUpdate() *PipelineInitTree_Secret_File_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *PipelineInitTree_Secret_File) GetDelete() *PipelineInitTree_Secret_File_Delete {
	if x != nil {
		return x.Delete
	}
	return nil
}

type PipelineInitTree_Secret_List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PipelineInitTree_Secret_List) Reset() {
	*x = PipelineInitTree_Secret_List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_List) ProtoMessage() {}

func (x *PipelineInitTree_Secret_List) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_List.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_List) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 4}
}

type PipelineInitTree_Secret_Text_Get struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PipelineInitTree_Secret_Text_Get) Reset() {
	*x = PipelineInitTree_Secret_Text_Get{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_Text_Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_Text_Get) ProtoMessage() {}

func (x *PipelineInitTree_Secret_Text_Get) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_Text_Get.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_Text_Get) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 0, 0}
}

func (x *PipelineInitTree_Secret_Text_Get) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PipelineInitTree_Secret_Text_Create struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PipelineInitTree_Secret_Text_Create) Reset() {
	*x = PipelineInitTree_Secret_Text_Create{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_Text_Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_Text_Create) ProtoMessage() {}

func (x *PipelineInitTree_Secret_Text_Create) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_Text_Create.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_Text_Create) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 0, 1}
}

func (x *PipelineInitTree_Secret_Text_Create) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type PipelineInitTree_Secret_Text_Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PipelineInitTree_Secret_Text_Update) Reset() {
	*x = PipelineInitTree_Secret_Text_Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_Text_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_Text_Update) ProtoMessage() {}

func (x *PipelineInitTree_Secret_Text_Update) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_Text_Update.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_Text_Update) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 0, 2}
}

func (x *PipelineInitTree_Secret_Text_Update) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PipelineInitTree_Secret_Text_Update) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type PipelineInitTree_Secret_Text_Delete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PipelineInitTree_Secret_Text_Delete) Reset() {
	*x = PipelineInitTree_Secret_Text_Delete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_Text_Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_Text_Delete) ProtoMessage() {}

func (x *PipelineInitTree_Secret_Text_Delete) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_Text_Delete.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_Text_Delete) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 0, 3}
}

func (x *PipelineInitTree_Secret_Text_Delete) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PipelineInitTree_Secret_LoginPassword_Get struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PipelineInitTree_Secret_LoginPassword_Get) Reset() {
	*x = PipelineInitTree_Secret_LoginPassword_Get{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_LoginPassword_Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_LoginPassword_Get) ProtoMessage() {}

func (x *PipelineInitTree_Secret_LoginPassword_Get) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_LoginPassword_Get.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_LoginPassword_Get) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 1, 0}
}

func (x *PipelineInitTree_Secret_LoginPassword_Get) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PipelineInitTree_Secret_LoginPassword_Create struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *PipelineInitTree_Secret_LoginPassword_Create) Reset() {
	*x = PipelineInitTree_Secret_LoginPassword_Create{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_LoginPassword_Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_LoginPassword_Create) ProtoMessage() {}

func (x *PipelineInitTree_Secret_LoginPassword_Create) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_LoginPassword_Create.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_LoginPassword_Create) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 1, 1}
}

func (x *PipelineInitTree_Secret_LoginPassword_Create) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *PipelineInitTree_Secret_LoginPassword_Create) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PipelineInitTree_Secret_LoginPassword_Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Login    string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *PipelineInitTree_Secret_LoginPassword_Update) Reset() {
	*x = PipelineInitTree_Secret_LoginPassword_Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_LoginPassword_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_LoginPassword_Update) ProtoMessage() {}

func (x *PipelineInitTree_Secret_LoginPassword_Update) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_LoginPassword_Update.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_LoginPassword_Update) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 1, 2}
}

func (x *PipelineInitTree_Secret_LoginPassword_Update) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PipelineInitTree_Secret_LoginPassword_Update) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *PipelineInitTree_Secret_LoginPassword_Update) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PipelineInitTree_Secret_LoginPassword_Delete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PipelineInitTree_Secret_LoginPassword_Delete) Reset() {
	*x = PipelineInitTree_Secret_LoginPassword_Delete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_LoginPassword_Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_LoginPassword_Delete) ProtoMessage() {}

func (x *PipelineInitTree_Secret_LoginPassword_Delete) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_LoginPassword_Delete.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_LoginPassword_Delete) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 1, 3}
}

func (x *PipelineInitTree_Secret_LoginPassword_Delete) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PipelineInitTree_Secret_CreditCard_Get struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PipelineInitTree_Secret_CreditCard_Get) Reset() {
	*x = PipelineInitTree_Secret_CreditCard_Get{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_CreditCard_Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_CreditCard_Get) ProtoMessage() {}

func (x *PipelineInitTree_Secret_CreditCard_Get) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_CreditCard_Get.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_CreditCard_Get) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 2, 0}
}

func (x *PipelineInitTree_Secret_CreditCard_Get) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PipelineInitTree_Secret_CreditCard_Create struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardNumber string `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardHolder string `protobuf:"bytes,2,opt,name=card_holder,json=cardHolder,proto3" json:"card_holder,omitempty"`
	ValidTill  string `protobuf:"bytes,3,opt,name=valid_till,json=validTill,proto3" json:"valid_till,omitempty"`
	Cvc        string `protobuf:"bytes,4,opt,name=cvc,proto3" json:"cvc,omitempty"`
}

func (x *PipelineInitTree_Secret_CreditCard_Create) Reset() {
	*x = PipelineInitTree_Secret_CreditCard_Create{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_CreditCard_Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_CreditCard_Create) ProtoMessage() {}

func (x *PipelineInitTree_Secret_CreditCard_Create) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_CreditCard_Create.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_CreditCard_Create) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 2, 1}
}

func (x *PipelineInitTree_Secret_CreditCard_Create) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *PipelineInitTree_Secret_CreditCard_Create) GetCardHolder() string {
	if x != nil {
		return x.CardHolder
	}
	return ""
}

func (x *PipelineInitTree_Secret_CreditCard_Create) GetValidTill() string {
	if x != nil {
		return x.ValidTill
	}
	return ""
}

func (x *PipelineInitTree_Secret_CreditCard_Create) GetCvc() string {
	if x != nil {
		return x.Cvc
	}
	return ""
}

type PipelineInitTree_Secret_CreditCard_Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CardNumber string `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardHolder string `protobuf:"bytes,3,opt,name=card_holder,json=cardHolder,proto3" json:"card_holder,omitempty"`
	ValidTill  string `protobuf:"bytes,4,opt,name=valid_till,json=validTill,proto3" json:"valid_till,omitempty"`
	Cvc        string `protobuf:"bytes,5,opt,name=cvc,proto3" json:"cvc,omitempty"`
}

func (x *PipelineInitTree_Secret_CreditCard_Update) Reset() {
	*x = PipelineInitTree_Secret_CreditCard_Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_CreditCard_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_CreditCard_Update) ProtoMessage() {}

func (x *PipelineInitTree_Secret_CreditCard_Update) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_CreditCard_Update.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_CreditCard_Update) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 2, 2}
}

func (x *PipelineInitTree_Secret_CreditCard_Update) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PipelineInitTree_Secret_CreditCard_Update) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *PipelineInitTree_Secret_CreditCard_Update) GetCardHolder() string {
	if x != nil {
		return x.CardHolder
	}
	return ""
}

func (x *PipelineInitTree_Secret_CreditCard_Update) GetValidTill() string {
	if x != nil {
		return x.ValidTill
	}
	return ""
}

func (x *PipelineInitTree_Secret_CreditCard_Update) GetCvc() string {
	if x != nil {
		return x.Cvc
	}
	return ""
}

type PipelineInitTree_Secret_CreditCard_Delete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PipelineInitTree_Secret_CreditCard_Delete) Reset() {
	*x = PipelineInitTree_Secret_CreditCard_Delete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_CreditCard_Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_CreditCard_Delete) ProtoMessage() {}

func (x *PipelineInitTree_Secret_CreditCard_Delete) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_CreditCard_Delete.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_CreditCard_Delete) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 2, 3}
}

func (x *PipelineInitTree_Secret_CreditCard_Delete) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PipelineInitTree_Secret_File_Download struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FilePath string `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
}

func (x *PipelineInitTree_Secret_File_Download) Reset() {
	*x = PipelineInitTree_Secret_File_Download{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_File_Download) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_File_Download) ProtoMessage() {}

func (x *PipelineInitTree_Secret_File_Download) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_File_Download.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_File_Download) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 3, 0}
}

func (x *PipelineInitTree_Secret_File_Download) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PipelineInitTree_Secret_File_Download) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type PipelineInitTree_Secret_File_Upload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
}

func (x *PipelineInitTree_Secret_File_Upload) Reset() {
	*x = PipelineInitTree_Secret_File_Upload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_File_Upload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_File_Upload) ProtoMessage() {}

func (x *PipelineInitTree_Secret_File_Upload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_File_Upload.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_File_Upload) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 3, 1}
}

func (x *PipelineInitTree_Secret_File_Upload) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type PipelineInitTree_Secret_File_Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FilePath string `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
}

func (x *PipelineInitTree_Secret_File_Update) Reset() {
	*x = PipelineInitTree_Secret_File_Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_File_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_File_Update) ProtoMessage() {}

func (x *PipelineInitTree_Secret_File_Update) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_File_Update.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_File_Update) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 3, 2}
}

func (x *PipelineInitTree_Secret_File_Update) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PipelineInitTree_Secret_File_Update) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type PipelineInitTree_Secret_File_Delete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PipelineInitTree_Secret_File_Delete) Reset() {
	*x = PipelineInitTree_Secret_File_Delete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pipeline_tree_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineInitTree_Secret_File_Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineInitTree_Secret_File_Delete) ProtoMessage() {}

func (x *PipelineInitTree_Secret_File_Delete) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_tree_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineInitTree_Secret_File_Delete.ProtoReflect.Descriptor instead.
func (*PipelineInitTree_Secret_File_Delete) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_tree_proto_rawDescGZIP(), []int{0, 1, 3, 3}
}

func (x *PipelineInitTree_Secret_File_Delete) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_pipeline_tree_proto protoreflect.FileDescriptor

var file_proto_pipeline_tree_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x2f, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x69, 0x70,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0xf9, 0x14, 0x0a, 0x10, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x69,
	0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49,
	0x6e, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74,
	0x54, 0x72, 0x65, 0x65, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x06, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x1a, 0x90, 0x01, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x47, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2b, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69, 0x70,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x2e, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x08,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x1a, 0x3c, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x1a, 0xd8, 0x12, 0x0a, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x12, 0x3a, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x2e, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x56, 0x0a,
	0x0e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x65,
	0x65, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x4d, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x5f,
	0x63, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x69, 0x70,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e,
	0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x43, 0x72,
	0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74,
	0x43, 0x61, 0x72, 0x64, 0x12, 0x3a, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69,
	0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x2e, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65,
	0x12, 0x3a, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x63, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26,
	0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x96, 0x03, 0x0a,
	0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x3c, 0x0a, 0x03, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69,
	0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x2e, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x03,
	0x67, 0x65, 0x74, 0x12, 0x45, 0x0a, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50,
	0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x2e,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x45, 0x0a, 0x06, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x69, 0x70,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e,
	0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x54, 0x65,
	0x78, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x45, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69, 0x70,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x2e, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x1a, 0x15, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a,
	0x1c, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x2c, 0x0a,
	0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x18, 0x0a, 0x06, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x1a, 0xff, 0x03, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x45, 0x0a, 0x03, 0x67, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e,
	0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65,
	0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x03, 0x67, 0x65, 0x74, 0x12, 0x4e,
	0x0a, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36,
	0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x4e,
	0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36,
	0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x4e,
	0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36,
	0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x1a, 0x15,
	0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x3a, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x1a, 0x4a, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x1a, 0x18, 0x0a,
	0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a, 0xf3, 0x04, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x64,
	0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x42, 0x0a, 0x03, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50,
	0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x2e,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72,
	0x64, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x03, 0x67, 0x65, 0x74, 0x12, 0x4b, 0x0a, 0x06, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x70, 0x69, 0x70,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e,
	0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x43, 0x72,
	0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x4b, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x54,
	0x72, 0x65, 0x65, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69,
	0x74, 0x43, 0x61, 0x72, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x06, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x4b, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e,
	0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65,
	0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61,
	0x72, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x1a, 0x15, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x7b, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x68, 0x6f, 0x6c, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x48, 0x6f,
	0x6c, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x74, 0x69,
	0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x54,
	0x69, 0x6c, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x76, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x63, 0x76, 0x63, 0x1a, 0x8b, 0x01, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x48, 0x6f, 0x6c, 0x64,
	0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x74, 0x69, 0x6c, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x54, 0x69, 0x6c,
	0x6c, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x76, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x63, 0x76, 0x63, 0x1a, 0x18, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a, 0xd9, 0x03,
	0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x4b, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74,
	0x54, 0x72, 0x65, 0x65, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x45, 0x0a, 0x06, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50,
	0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x2e,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x06, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x45, 0x0a, 0x06, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x69, 0x70,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e,
	0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x45, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69, 0x70,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x2e, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x1a, 0x37, 0x0a, 0x08, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x1a, 0x25, 0x0a, 0x06, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x1a, 0x35, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x1a,
	0x18, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x06, 0x0a, 0x04, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x6c, 0x69, 0x67, 0x61, 0x6e, 0x67, 0x2f, 0x47, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x69, 0x70, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_pipeline_tree_proto_rawDescOnce sync.Once
	file_proto_pipeline_tree_proto_rawDescData = file_proto_pipeline_tree_proto_rawDesc
)

func file_proto_pipeline_tree_proto_rawDescGZIP() []byte {
	file_proto_pipeline_tree_proto_rawDescOnce.Do(func() {
		file_proto_pipeline_tree_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pipeline_tree_proto_rawDescData)
	})
	return file_proto_pipeline_tree_proto_rawDescData
}

var file_proto_pipeline_tree_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_pipeline_tree_proto_goTypes = []interface{}{
	(*PipelineInitTree)(nil),                             // 0: pipeline.PipelineInitTree
	(*PipelineInitTree_Account)(nil),                     // 1: pipeline.PipelineInitTree.Account
	(*PipelineInitTree_Secret)(nil),                      // 2: pipeline.PipelineInitTree.Secret
	(*PipelineInitTree_Account_Register)(nil),            // 3: pipeline.PipelineInitTree.Account.Register
	(*PipelineInitTree_Secret_Text)(nil),                 // 4: pipeline.PipelineInitTree.Secret.Text
	(*PipelineInitTree_Secret_LoginPassword)(nil),        // 5: pipeline.PipelineInitTree.Secret.LoginPassword
	(*PipelineInitTree_Secret_CreditCard)(nil),           // 6: pipeline.PipelineInitTree.Secret.CreditCard
	(*PipelineInitTree_Secret_File)(nil),                 // 7: pipeline.PipelineInitTree.Secret.File
	(*PipelineInitTree_Secret_List)(nil),                 // 8: pipeline.PipelineInitTree.Secret.List
	(*PipelineInitTree_Secret_Text_Get)(nil),             // 9: pipeline.PipelineInitTree.Secret.Text.Get
	(*PipelineInitTree_Secret_Text_Create)(nil),          // 10: pipeline.PipelineInitTree.Secret.Text.Create
	(*PipelineInitTree_Secret_Text_Update)(nil),          // 11: pipeline.PipelineInitTree.Secret.Text.Update
	(*PipelineInitTree_Secret_Text_Delete)(nil),          // 12: pipeline.PipelineInitTree.Secret.Text.Delete
	(*PipelineInitTree_Secret_LoginPassword_Get)(nil),    // 13: pipeline.PipelineInitTree.Secret.LoginPassword.Get
	(*PipelineInitTree_Secret_LoginPassword_Create)(nil), // 14: pipeline.PipelineInitTree.Secret.LoginPassword.Create
	(*PipelineInitTree_Secret_LoginPassword_Update)(nil), // 15: pipeline.PipelineInitTree.Secret.LoginPassword.Update
	(*PipelineInitTree_Secret_LoginPassword_Delete)(nil), // 16: pipeline.PipelineInitTree.Secret.LoginPassword.Delete
	(*PipelineInitTree_Secret_CreditCard_Get)(nil),       // 17: pipeline.PipelineInitTree.Secret.CreditCard.Get
	(*PipelineInitTree_Secret_CreditCard_Create)(nil),    // 18: pipeline.PipelineInitTree.Secret.CreditCard.Create
	(*PipelineInitTree_Secret_CreditCard_Update)(nil),    // 19: pipeline.PipelineInitTree.Secret.CreditCard.Update
	(*PipelineInitTree_Secret_CreditCard_Delete)(nil),    // 20: pipeline.PipelineInitTree.Secret.CreditCard.Delete
	(*PipelineInitTree_Secret_File_Download)(nil),        // 21: pipeline.PipelineInitTree.Secret.File.Download
	(*PipelineInitTree_Secret_File_Upload)(nil),          // 22: pipeline.PipelineInitTree.Secret.File.Upload
	(*PipelineInitTree_Secret_File_Update)(nil),          // 23: pipeline.PipelineInitTree.Secret.File.Update
	(*PipelineInitTree_Secret_File_Delete)(nil),          // 24: pipeline.PipelineInitTree.Secret.File.Delete
}
var file_proto_pipeline_tree_proto_depIdxs = []int32{
	1,  // 0: pipeline.PipelineInitTree.account:type_name -> pipeline.PipelineInitTree.Account
	2,  // 1: pipeline.PipelineInitTree.secret:type_name -> pipeline.PipelineInitTree.Secret
	3,  // 2: pipeline.PipelineInitTree.Account.register:type_name -> pipeline.PipelineInitTree.Account.Register
	4,  // 3: pipeline.PipelineInitTree.Secret.text:type_name -> pipeline.PipelineInitTree.Secret.Text
	5,  // 4: pipeline.PipelineInitTree.Secret.login_password:type_name -> pipeline.PipelineInitTree.Secret.LoginPassword
	6,  // 5: pipeline.PipelineInitTree.Secret.credit_card:type_name -> pipeline.PipelineInitTree.Secret.CreditCard
	7,  // 6: pipeline.PipelineInitTree.Secret.file:type_name -> pipeline.PipelineInitTree.Secret.File
	8,  // 7: pipeline.PipelineInitTree.Secret.list:type_name -> pipeline.PipelineInitTree.Secret.List
	9,  // 8: pipeline.PipelineInitTree.Secret.Text.get:type_name -> pipeline.PipelineInitTree.Secret.Text.Get
	10, // 9: pipeline.PipelineInitTree.Secret.Text.create:type_name -> pipeline.PipelineInitTree.Secret.Text.Create
	11, // 10: pipeline.PipelineInitTree.Secret.Text.update:type_name -> pipeline.PipelineInitTree.Secret.Text.Update
	12, // 11: pipeline.PipelineInitTree.Secret.Text.delete:type_name -> pipeline.PipelineInitTree.Secret.Text.Delete
	13, // 12: pipeline.PipelineInitTree.Secret.LoginPassword.get:type_name -> pipeline.PipelineInitTree.Secret.LoginPassword.Get
	14, // 13: pipeline.PipelineInitTree.Secret.LoginPassword.create:type_name -> pipeline.PipelineInitTree.Secret.LoginPassword.Create
	15, // 14: pipeline.PipelineInitTree.Secret.LoginPassword.update:type_name -> pipeline.PipelineInitTree.Secret.LoginPassword.Update
	16, // 15: pipeline.PipelineInitTree.Secret.LoginPassword.delete:type_name -> pipeline.PipelineInitTree.Secret.LoginPassword.Delete
	17, // 16: pipeline.PipelineInitTree.Secret.CreditCard.get:type_name -> pipeline.PipelineInitTree.Secret.CreditCard.Get
	18, // 17: pipeline.PipelineInitTree.Secret.CreditCard.create:type_name -> pipeline.PipelineInitTree.Secret.CreditCard.Create
	19, // 18: pipeline.PipelineInitTree.Secret.CreditCard.update:type_name -> pipeline.PipelineInitTree.Secret.CreditCard.Update
	20, // 19: pipeline.PipelineInitTree.Secret.CreditCard.delete:type_name -> pipeline.PipelineInitTree.Secret.CreditCard.Delete
	21, // 20: pipeline.PipelineInitTree.Secret.File.download:type_name -> pipeline.PipelineInitTree.Secret.File.Download
	22, // 21: pipeline.PipelineInitTree.Secret.File.upload:type_name -> pipeline.PipelineInitTree.Secret.File.Upload
	23, // 22: pipeline.PipelineInitTree.Secret.File.update:type_name -> pipeline.PipelineInitTree.Secret.File.Update
	24, // 23: pipeline.PipelineInitTree.Secret.File.delete:type_name -> pipeline.PipelineInitTree.Secret.File.Delete
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_proto_pipeline_tree_proto_init() }
func file_proto_pipeline_tree_proto_init() {
	if File_proto_pipeline_tree_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pipeline_tree_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Account_Register); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_Text); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_LoginPassword); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_CreditCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_Text_Get); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_Text_Create); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_Text_Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_Text_Delete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_LoginPassword_Get); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_LoginPassword_Create); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_LoginPassword_Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_LoginPassword_Delete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_CreditCard_Get); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_CreditCard_Create); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_CreditCard_Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_CreditCard_Delete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_File_Download); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_File_Upload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_File_Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pipeline_tree_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineInitTree_Secret_File_Delete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pipeline_tree_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_pipeline_tree_proto_goTypes,
		DependencyIndexes: file_proto_pipeline_tree_proto_depIdxs,
		MessageInfos:      file_proto_pipeline_tree_proto_msgTypes,
	}.Build()
	File_proto_pipeline_tree_proto = out.File
	file_proto_pipeline_tree_proto_rawDesc = nil
	file_proto_pipeline_tree_proto_goTypes = nil
	file_proto_pipeline_tree_proto_depIdxs = nil
}
