// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: proto/secret/secret_service.proto

package secret

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SecretType SecretType `protobuf:"varint,2,opt,name=secret_type,json=secretType,proto3,enum=secret.SecretType" json:"secret_type,omitempty"`
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secret_secret_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secret_secret_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_secret_secret_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSecretRequest) GetSecretType() SecretType {
	if x != nil {
		return x.SecretType
	}
	return SecretType_UNSPECIFIED
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SecretType SecretType `protobuf:"varint,2,opt,name=secret_type,json=secretType,proto3,enum=secret.SecretType" json:"secret_type,omitempty"`
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secret_secret_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secret_secret_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_secret_secret_service_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteSecretRequest) GetSecretType() SecretType {
	if x != nil {
		return x.SecretType
	}
	return SecretType_UNSPECIFIED
}

type GetSecretDescriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSecretDescriptionRequest) Reset() {
	*x = GetSecretDescriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secret_secret_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSecretDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretDescriptionRequest) ProtoMessage() {}

func (x *GetSecretDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secret_secret_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretDescriptionRequest.ProtoReflect.Descriptor instead.
func (*GetSecretDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_secret_secret_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetSecretDescriptionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Secret:
	//
	//	*CreateSecretRequest_Text
	//	*CreateSecretRequest_LoginPassword
	//	*CreateSecretRequest_CreditCard
	//	*CreateSecretRequest_File
	Secret isCreateSecretRequest_Secret `protobuf_oneof:"secret"`
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secret_secret_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secret_secret_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_secret_secret_service_proto_rawDescGZIP(), []int{3}
}

func (m *CreateSecretRequest) GetSecret() isCreateSecretRequest_Secret {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (x *CreateSecretRequest) GetText() *PlainText {
	if x, ok := x.GetSecret().(*CreateSecretRequest_Text); ok {
		return x.Text
	}
	return nil
}

func (x *CreateSecretRequest) GetLoginPassword() *LoginPassword {
	if x, ok := x.GetSecret().(*CreateSecretRequest_LoginPassword); ok {
		return x.LoginPassword
	}
	return nil
}

func (x *CreateSecretRequest) GetCreditCard() *CreditCard {
	if x, ok := x.GetSecret().(*CreateSecretRequest_CreditCard); ok {
		return x.CreditCard
	}
	return nil
}

func (x *CreateSecretRequest) GetFile() *File {
	if x, ok := x.GetSecret().(*CreateSecretRequest_File); ok {
		return x.File
	}
	return nil
}

type isCreateSecretRequest_Secret interface {
	isCreateSecretRequest_Secret()
}

type CreateSecretRequest_Text struct {
	Text *PlainText `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type CreateSecretRequest_LoginPassword struct {
	LoginPassword *LoginPassword `protobuf:"bytes,2,opt,name=login_password,json=loginPassword,proto3,oneof"`
}

type CreateSecretRequest_CreditCard struct {
	CreditCard *CreditCard `protobuf:"bytes,3,opt,name=credit_card,json=creditCard,proto3,oneof"`
}

type CreateSecretRequest_File struct {
	File *File `protobuf:"bytes,4,opt,name=file,proto3,oneof"`
}

func (*CreateSecretRequest_Text) isCreateSecretRequest_Secret() {}

func (*CreateSecretRequest_LoginPassword) isCreateSecretRequest_Secret() {}

func (*CreateSecretRequest_CreditCard) isCreateSecretRequest_Secret() {}

func (*CreateSecretRequest_File) isCreateSecretRequest_Secret() {}

type UpdateSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are assignable to Secret:
	//
	//	*UpdateSecretRequest_Text
	//	*UpdateSecretRequest_LoginPassword
	//	*UpdateSecretRequest_CreditCard
	//	*UpdateSecretRequest_File
	Secret isUpdateSecretRequest_Secret `protobuf_oneof:"secret"`
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secret_secret_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secret_secret_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_secret_secret_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (m *UpdateSecretRequest) GetSecret() isUpdateSecretRequest_Secret {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (x *UpdateSecretRequest) GetText() *PlainText {
	if x, ok := x.GetSecret().(*UpdateSecretRequest_Text); ok {
		return x.Text
	}
	return nil
}

func (x *UpdateSecretRequest) GetLoginPassword() *LoginPassword {
	if x, ok := x.GetSecret().(*UpdateSecretRequest_LoginPassword); ok {
		return x.LoginPassword
	}
	return nil
}

func (x *UpdateSecretRequest) GetCreditCard() *CreditCard {
	if x, ok := x.GetSecret().(*UpdateSecretRequest_CreditCard); ok {
		return x.CreditCard
	}
	return nil
}

func (x *UpdateSecretRequest) GetFile() *File {
	if x, ok := x.GetSecret().(*UpdateSecretRequest_File); ok {
		return x.File
	}
	return nil
}

type isUpdateSecretRequest_Secret interface {
	isUpdateSecretRequest_Secret()
}

type UpdateSecretRequest_Text struct {
	Text *PlainText `protobuf:"bytes,11,opt,name=text,proto3,oneof"`
}

type UpdateSecretRequest_LoginPassword struct {
	LoginPassword *LoginPassword `protobuf:"bytes,12,opt,name=login_password,json=loginPassword,proto3,oneof"`
}

type UpdateSecretRequest_CreditCard struct {
	CreditCard *CreditCard `protobuf:"bytes,13,opt,name=credit_card,json=creditCard,proto3,oneof"`
}

type UpdateSecretRequest_File struct {
	File *File `protobuf:"bytes,14,opt,name=file,proto3,oneof"`
}

func (*UpdateSecretRequest_Text) isUpdateSecretRequest_Secret() {}

func (*UpdateSecretRequest_LoginPassword) isUpdateSecretRequest_Secret() {}

func (*UpdateSecretRequest_CreditCard) isUpdateSecretRequest_Secret() {}

func (*UpdateSecretRequest_File) isUpdateSecretRequest_Secret() {}

type ListSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSecretRequest) Reset() {
	*x = ListSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secret_secret_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretRequest) ProtoMessage() {}

func (x *ListSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secret_secret_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretRequest.ProtoReflect.Descriptor instead.
func (*ListSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_secret_secret_service_proto_rawDescGZIP(), []int{5}
}

type ListSecretResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secrets []*SecretDescription `protobuf:"bytes,2,rep,name=secrets,proto3" json:"secrets,omitempty"`
}

func (x *ListSecretResponse) Reset() {
	*x = ListSecretResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secret_secret_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretResponse) ProtoMessage() {}

func (x *ListSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secret_secret_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretResponse.ProtoReflect.Descriptor instead.
func (*ListSecretResponse) Descriptor() ([]byte, []int) {
	return file_proto_secret_secret_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListSecretResponse) GetSecrets() []*SecretDescription {
	if x != nil {
		return x.Secrets
	}
	return nil
}

var File_proto_secret_secret_service_proto protoreflect.FileDescriptor

var file_proto_secret_secret_service_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2f, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x1a, 0x19, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x33, 0x0a, 0x0b, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x5a, 0x0a, 0x13,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x33, 0x0a, 0x0b, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x2d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xe3, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x27, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x54, 0x65, 0x78, 0x74,
	0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x3e, 0x0a, 0x0e, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x35, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64,
	0x69, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72,
	0x64, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12,
	0x22, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x04, 0x66,
	0x69, 0x6c, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0xf3, 0x01,
	0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x50, 0x6c, 0x61,
	0x69, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x3e,
	0x0a, 0x0e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52,
	0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x35,
	0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x43, 0x72, 0x65,
	0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x69,
	0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x22, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x48, 0x00, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33,
	0x0a, 0x07, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x73, 0x32, 0x94, 0x03, 0x0a, 0x0d, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x19, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x18, 0x2e,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x40, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x40, 0x0a, 0x06, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x06, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x69, 0x67, 0x61, 0x6e, 0x67,
	0x2f, 0x47, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_secret_secret_service_proto_rawDescOnce sync.Once
	file_proto_secret_secret_service_proto_rawDescData = file_proto_secret_secret_service_proto_rawDesc
)

func file_proto_secret_secret_service_proto_rawDescGZIP() []byte {
	file_proto_secret_secret_service_proto_rawDescOnce.Do(func() {
		file_proto_secret_secret_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_secret_secret_service_proto_rawDescData)
	})
	return file_proto_secret_secret_service_proto_rawDescData
}

var file_proto_secret_secret_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_secret_secret_service_proto_goTypes = []interface{}{
	(*GetSecretRequest)(nil),            // 0: secret.GetSecretRequest
	(*DeleteSecretRequest)(nil),         // 1: secret.DeleteSecretRequest
	(*GetSecretDescriptionRequest)(nil), // 2: secret.GetSecretDescriptionRequest
	(*CreateSecretRequest)(nil),         // 3: secret.CreateSecretRequest
	(*UpdateSecretRequest)(nil),         // 4: secret.UpdateSecretRequest
	(*ListSecretRequest)(nil),           // 5: secret.ListSecretRequest
	(*ListSecretResponse)(nil),          // 6: secret.ListSecretResponse
	(SecretType)(0),                     // 7: secret.SecretType
	(*PlainText)(nil),                   // 8: secret.PlainText
	(*LoginPassword)(nil),               // 9: secret.LoginPassword
	(*CreditCard)(nil),                  // 10: secret.CreditCard
	(*File)(nil),                        // 11: secret.File
	(*SecretDescription)(nil),           // 12: secret.SecretDescription
	(*Secret)(nil),                      // 13: secret.Secret
	(*empty.Empty)(nil),                 // 14: google.protobuf.Empty
}
var file_proto_secret_secret_service_proto_depIdxs = []int32{
	7,  // 0: secret.GetSecretRequest.secret_type:type_name -> secret.SecretType
	7,  // 1: secret.DeleteSecretRequest.secret_type:type_name -> secret.SecretType
	8,  // 2: secret.CreateSecretRequest.text:type_name -> secret.PlainText
	9,  // 3: secret.CreateSecretRequest.login_password:type_name -> secret.LoginPassword
	10, // 4: secret.CreateSecretRequest.credit_card:type_name -> secret.CreditCard
	11, // 5: secret.CreateSecretRequest.file:type_name -> secret.File
	8,  // 6: secret.UpdateSecretRequest.text:type_name -> secret.PlainText
	9,  // 7: secret.UpdateSecretRequest.login_password:type_name -> secret.LoginPassword
	10, // 8: secret.UpdateSecretRequest.credit_card:type_name -> secret.CreditCard
	11, // 9: secret.UpdateSecretRequest.file:type_name -> secret.File
	12, // 10: secret.ListSecretResponse.secrets:type_name -> secret.SecretDescription
	2,  // 11: secret.SecretService.GetDescription:input_type -> secret.GetSecretDescriptionRequest
	5,  // 12: secret.SecretService.List:input_type -> secret.ListSecretRequest
	0,  // 13: secret.SecretService.Get:input_type -> secret.GetSecretRequest
	3,  // 14: secret.SecretService.Create:input_type -> secret.CreateSecretRequest
	4,  // 15: secret.SecretService.Update:input_type -> secret.UpdateSecretRequest
	1,  // 16: secret.SecretService.Delete:input_type -> secret.DeleteSecretRequest
	12, // 17: secret.SecretService.GetDescription:output_type -> secret.SecretDescription
	6,  // 18: secret.SecretService.List:output_type -> secret.ListSecretResponse
	13, // 19: secret.SecretService.Get:output_type -> secret.Secret
	12, // 20: secret.SecretService.Create:output_type -> secret.SecretDescription
	12, // 21: secret.SecretService.Update:output_type -> secret.SecretDescription
	14, // 22: secret.SecretService.Delete:output_type -> google.protobuf.Empty
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_secret_secret_service_proto_init() }
func file_proto_secret_secret_service_proto_init() {
	if File_proto_secret_secret_service_proto != nil {
		return
	}
	file_proto_secret_secret_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_secret_secret_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secret_secret_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secret_secret_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSecretDescriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secret_secret_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secret_secret_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secret_secret_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secret_secret_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSecretResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_secret_secret_service_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*CreateSecretRequest_Text)(nil),
		(*CreateSecretRequest_LoginPassword)(nil),
		(*CreateSecretRequest_CreditCard)(nil),
		(*CreateSecretRequest_File)(nil),
	}
	file_proto_secret_secret_service_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*UpdateSecretRequest_Text)(nil),
		(*UpdateSecretRequest_LoginPassword)(nil),
		(*UpdateSecretRequest_CreditCard)(nil),
		(*UpdateSecretRequest_File)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_secret_secret_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_secret_secret_service_proto_goTypes,
		DependencyIndexes: file_proto_secret_secret_service_proto_depIdxs,
		MessageInfos:      file_proto_secret_secret_service_proto_msgTypes,
	}.Build()
	File_proto_secret_secret_service_proto = out.File
	file_proto_secret_secret_service_proto_rawDesc = nil
	file_proto_secret_secret_service_proto_goTypes = nil
	file_proto_secret_secret_service_proto_depIdxs = nil
}
