// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: proto/config/log_level.proto

package logging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_LOGLEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_DEBUG                LogLevel = 4
	LogLevel_INFO                 LogLevel = 3
	LogLevel_WARNING              LogLevel = 2
	LogLevel_CRITICAL             LogLevel = 1
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOGLEVEL_UNSPECIFIED",
		4: "DEBUG",
		3: "INFO",
		2: "WARNING",
		1: "CRITICAL",
	}
	LogLevel_value = map[string]int32{
		"LOGLEVEL_UNSPECIFIED": 0,
		"DEBUG":                4,
		"INFO":                 3,
		"WARNING":              2,
		"CRITICAL":             1,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_config_log_level_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_proto_config_log_level_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_config_log_level_proto_rawDescGZIP(), []int{0}
}

var File_proto_config_log_level_proto protoreflect.FileDescriptor

var file_proto_config_log_level_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x6c,
	0x6f, 0x67, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x6c, 0x6f, 0x67, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x2a, 0x54, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x14,
	0x4c, 0x4f, 0x47, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x45, 0x42, 0x55, 0x47, 0x10,
	0x04, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x57,
	0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x52, 0x49, 0x54,
	0x49, 0x43, 0x41, 0x4c, 0x10, 0x01, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x69, 0x67, 0x61, 0x6e, 0x67, 0x2f, 0x47, 0x6f, 0x70,
	0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_config_log_level_proto_rawDescOnce sync.Once
	file_proto_config_log_level_proto_rawDescData = file_proto_config_log_level_proto_rawDesc
)

func file_proto_config_log_level_proto_rawDescGZIP() []byte {
	file_proto_config_log_level_proto_rawDescOnce.Do(func() {
		file_proto_config_log_level_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_config_log_level_proto_rawDescData)
	})
	return file_proto_config_log_level_proto_rawDescData
}

var file_proto_config_log_level_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_config_log_level_proto_goTypes = []interface{}{
	(LogLevel)(0), // 0: config.log_level.LogLevel
}
var file_proto_config_log_level_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_config_log_level_proto_init() }
func file_proto_config_log_level_proto_init() {
	if File_proto_config_log_level_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_config_log_level_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_config_log_level_proto_goTypes,
		DependencyIndexes: file_proto_config_log_level_proto_depIdxs,
		EnumInfos:         file_proto_config_log_level_proto_enumTypes,
	}.Build()
	File_proto_config_log_level_proto = out.File
	file_proto_config_log_level_proto_rawDesc = nil
	file_proto_config_log_level_proto_goTypes = nil
	file_proto_config_log_level_proto_depIdxs = nil
}
