// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: proto/secret/secret.proto

package secret

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretType int32

const (
	SecretType_UNSPECIFIED    SecretType = 0
	SecretType_TEXT           SecretType = 1
	SecretType_LOGIN_PASSWORD SecretType = 2
	SecretType_CREDIT_CARD    SecretType = 3
	SecretType_FILE           SecretType = 4
)

// Enum value maps for SecretType.
var (
	SecretType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "TEXT",
		2: "LOGIN_PASSWORD",
		3: "CREDIT_CARD",
		4: "FILE",
	}
	SecretType_value = map[string]int32{
		"UNSPECIFIED":    0,
		"TEXT":           1,
		"LOGIN_PASSWORD": 2,
		"CREDIT_CARD":    3,
		"FILE":           4,
	}
)

func (x SecretType) Enum() *SecretType {
	p := new(SecretType)
	*p = x
	return p
}

func (x SecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_secret_secret_proto_enumTypes[0].Descriptor()
}

func (SecretType) Type() protoreflect.EnumType {
	return &file_proto_secret_secret_proto_enumTypes[0]
}

func (x SecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretType.Descriptor instead.
func (SecretType) EnumDescriptor() ([]byte, []int) {
	return file_proto_secret_secret_proto_rawDescGZIP(), []int{0}
}

type SecretDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt  string     `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ModifiedAt string     `protobuf:"bytes,3,opt,name=modifiedAt,proto3" json:"modifiedAt,omitempty"`
	SecretType SecretType `protobuf:"varint,4,opt,name=secret_type,json=secretType,proto3,enum=secret.SecretType" json:"secret_type,omitempty"`
}

func (x *SecretDescription) Reset() {
	*x = SecretDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secret_secret_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretDescription) ProtoMessage() {}

func (x *SecretDescription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secret_secret_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretDescription.ProtoReflect.Descriptor instead.
func (*SecretDescription) Descriptor() ([]byte, []int) {
	return file_proto_secret_secret_proto_rawDescGZIP(), []int{0}
}

func (x *SecretDescription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretDescription) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SecretDescription) GetModifiedAt() string {
	if x != nil {
		return x.ModifiedAt
	}
	return ""
}

func (x *SecretDescription) GetSecretType() SecretType {
	if x != nil {
		return x.SecretType
	}
	return SecretType_UNSPECIFIED
}

type Secret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt  string `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ModifiedAt string `protobuf:"bytes,3,opt,name=modifiedAt,proto3" json:"modifiedAt,omitempty"`
	AccountID  string `protobuf:"bytes,4,opt,name=accountID,proto3" json:"accountID,omitempty"`
	// Types that are assignable to Secret:
	//
	//	*Secret_PlainText
	//	*Secret_LoginPassword
	//	*Secret_CreditCard
	//	*Secret_File
	Secret isSecret_Secret `protobuf_oneof:"secret"`
}

func (x *Secret) Reset() {
	*x = Secret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secret_secret_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secret_secret_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_proto_secret_secret_proto_rawDescGZIP(), []int{1}
}

func (x *Secret) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Secret) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Secret) GetModifiedAt() string {
	if x != nil {
		return x.ModifiedAt
	}
	return ""
}

func (x *Secret) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (m *Secret) GetSecret() isSecret_Secret {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (x *Secret) GetPlainText() *PlainText {
	if x, ok := x.GetSecret().(*Secret_PlainText); ok {
		return x.PlainText
	}
	return nil
}

func (x *Secret) GetLoginPassword() *LoginPassword {
	if x, ok := x.GetSecret().(*Secret_LoginPassword); ok {
		return x.LoginPassword
	}
	return nil
}

func (x *Secret) GetCreditCard() *CreditCard {
	if x, ok := x.GetSecret().(*Secret_CreditCard); ok {
		return x.CreditCard
	}
	return nil
}

func (x *Secret) GetFile() *File {
	if x, ok := x.GetSecret().(*Secret_File); ok {
		return x.File
	}
	return nil
}

type isSecret_Secret interface {
	isSecret_Secret()
}

type Secret_PlainText struct {
	PlainText *PlainText `protobuf:"bytes,11,opt,name=plain_text,json=plainText,proto3,oneof"`
}

type Secret_LoginPassword struct {
	LoginPassword *LoginPassword `protobuf:"bytes,12,opt,name=login_password,json=loginPassword,proto3,oneof"`
}

type Secret_CreditCard struct {
	CreditCard *CreditCard `protobuf:"bytes,13,opt,name=credit_card,json=creditCard,proto3,oneof"`
}

type Secret_File struct {
	File *File `protobuf:"bytes,14,opt,name=file,proto3,oneof"`
}

func (*Secret_PlainText) isSecret_Secret() {}

func (*Secret_LoginPassword) isSecret_Secret() {}

func (*Secret_CreditCard) isSecret_Secret() {}

func (*Secret_File) isSecret_Secret() {}

type PlainText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PlainText) Reset() {
	*x = PlainText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secret_secret_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlainText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlainText) ProtoMessage() {}

func (x *PlainText) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secret_secret_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlainText.ProtoReflect.Descriptor instead.
func (*PlainText) Descriptor() ([]byte, []int) {
	return file_proto_secret_secret_proto_rawDescGZIP(), []int{2}
}

func (x *PlainText) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type LoginPassword struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginPassword) Reset() {
	*x = LoginPassword{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secret_secret_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginPassword) ProtoMessage() {}

func (x *LoginPassword) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secret_secret_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginPassword.ProtoReflect.Descriptor instead.
func (*LoginPassword) Descriptor() ([]byte, []int) {
	return file_proto_secret_secret_proto_rawDescGZIP(), []int{3}
}

func (x *LoginPassword) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginPassword) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreditCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number         string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	CardholderName string `protobuf:"bytes,2,opt,name=cardholder_name,json=cardholderName,proto3" json:"cardholder_name,omitempty"`
	ValidTill      string `protobuf:"bytes,3,opt,name=valid_till,json=validTill,proto3" json:"valid_till,omitempty"`
	Cvc            string `protobuf:"bytes,4,opt,name=cvc,proto3" json:"cvc,omitempty"`
}

func (x *CreditCard) Reset() {
	*x = CreditCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secret_secret_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreditCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditCard) ProtoMessage() {}

func (x *CreditCard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secret_secret_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditCard.ProtoReflect.Descriptor instead.
func (*CreditCard) Descriptor() ([]byte, []int) {
	return file_proto_secret_secret_proto_rawDescGZIP(), []int{4}
}

func (x *CreditCard) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CreditCard) GetCardholderName() string {
	if x != nil {
		return x.CardholderName
	}
	return ""
}

func (x *CreditCard) GetValidTill() string {
	if x != nil {
		return x.ValidTill
	}
	return ""
}

func (x *CreditCard) GetCvc() string {
	if x != nil {
		return x.Cvc
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secret_secret_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secret_secret_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_proto_secret_secret_proto_rawDescGZIP(), []int{5}
}

func (x *File) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_secret_secret_proto protoreflect.FileDescriptor

var file_proto_secret_secret_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2f, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x22, 0x96, 0x01, 0x0a, 0x11, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x64,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x41, 0x74, 0x12, 0x33, 0x0a, 0x0b, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0xcd, 0x02, 0x0a,
	0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x44, 0x12, 0x32, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x2e, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x09, 0x70, 0x6c,
	0x61, 0x69, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x12, 0x3e, 0x0a, 0x0e, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x35, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x69,
	0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64,
	0x48, 0x00, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x22,
	0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x04, 0x66, 0x69,
	0x6c, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x1f, 0x0a, 0x09,
	0x50, 0x6c, 0x61, 0x69, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x41, 0x0a,
	0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x22, 0x7e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x61, 0x72, 0x64, 0x68, 0x6f,
	0x6c, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x63, 0x61, 0x72, 0x64, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x74, 0x69, 0x6c, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x54, 0x69, 0x6c, 0x6c, 0x12, 0x10,
	0x0a, 0x03, 0x63, 0x76, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x76, 0x63,
	0x22, 0x1a, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x56, 0x0a, 0x0a,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x54,
	0x45, 0x58, 0x54, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x50,
	0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x52, 0x45,
	0x44, 0x49, 0x54, 0x5f, 0x43, 0x41, 0x52, 0x44, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x49,
	0x4c, 0x45, 0x10, 0x04, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x69, 0x67, 0x61, 0x6e, 0x67, 0x2f, 0x47, 0x6f, 0x70, 0x68, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_secret_secret_proto_rawDescOnce sync.Once
	file_proto_secret_secret_proto_rawDescData = file_proto_secret_secret_proto_rawDesc
)

func file_proto_secret_secret_proto_rawDescGZIP() []byte {
	file_proto_secret_secret_proto_rawDescOnce.Do(func() {
		file_proto_secret_secret_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_secret_secret_proto_rawDescData)
	})
	return file_proto_secret_secret_proto_rawDescData
}

var file_proto_secret_secret_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_secret_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_secret_secret_proto_goTypes = []interface{}{
	(SecretType)(0),           // 0: secret.SecretType
	(*SecretDescription)(nil), // 1: secret.SecretDescription
	(*Secret)(nil),            // 2: secret.Secret
	(*PlainText)(nil),         // 3: secret.PlainText
	(*LoginPassword)(nil),     // 4: secret.LoginPassword
	(*CreditCard)(nil),        // 5: secret.CreditCard
	(*File)(nil),              // 6: secret.File
}
var file_proto_secret_secret_proto_depIdxs = []int32{
	0, // 0: secret.SecretDescription.secret_type:type_name -> secret.SecretType
	3, // 1: secret.Secret.plain_text:type_name -> secret.PlainText
	4, // 2: secret.Secret.login_password:type_name -> secret.LoginPassword
	5, // 3: secret.Secret.credit_card:type_name -> secret.CreditCard
	6, // 4: secret.Secret.file:type_name -> secret.File
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_secret_secret_proto_init() }
func file_proto_secret_secret_proto_init() {
	if File_proto_secret_secret_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_secret_secret_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secret_secret_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Secret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secret_secret_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlainText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secret_secret_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginPassword); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secret_secret_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreditCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secret_secret_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_secret_secret_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Secret_PlainText)(nil),
		(*Secret_LoginPassword)(nil),
		(*Secret_CreditCard)(nil),
		(*Secret_File)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_secret_secret_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_secret_secret_proto_goTypes,
		DependencyIndexes: file_proto_secret_secret_proto_depIdxs,
		EnumInfos:         file_proto_secret_secret_proto_enumTypes,
		MessageInfos:      file_proto_secret_secret_proto_msgTypes,
	}.Build()
	File_proto_secret_secret_proto = out.File
	file_proto_secret_secret_proto_rawDesc = nil
	file_proto_secret_secret_proto_goTypes = nil
	file_proto_secret_secret_proto_depIdxs = nil
}
